nodeLinker: pnp

packageExtensions:
  react-query@*:
    dependencies:
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.1.cjs
